global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['kafka-producer-service:8080']
        labels:
          application: 'kafka-producer-service'
          group: 'kafka-services'

  - job_name: 'kafka-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['kafka-consumer-service:8081']
        labels:
          application: 'kafka-consumer-service'
          group: 'kafka-services'

  - job_name: 'fs-consumer-raw-dump-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'fs-consumer-raw-dump-local-service:8084' ]
        labels:
          application: 'fs-consumer-raw-dump-local-service'
          group: 'kafka-consumer-services'

  - job_name: 'kafka-brokers'
    static_configs:
      - targets: ['broker-1:19092', 'broker-2:19092', 'broker-3:19092']
    metrics_path: /metrics

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse-server:9363']
    metrics_path: /metrics

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
